### ISSUE TITLE
Bug : fil d'actu 

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/co2#767]
![capture d ecran de 2018-03-14 11-26-21](https://user-images.githubusercontent.com/8775448/37388584-903e45c4-277a-11e8-990a-bed39b8395d4.png)

Code Erreur 500 : http://127.0.0.1/ph/co2/news/index/type/citoyens/id/55e042ffe41d754428848363/isLive/true/date/0?isFirst=1&tpl=co2&renderPartial=true

``` <h1>MongoResultException</h1>
<p>127.0.0.1:27017: The 'cursor' option is required, except for aggregate with the explain argument (/home/codev/dev/workspaceWeb/modules/citizenToolKit/models/Document.php:451)</p><pre>#0 /home/codev/dev/workspaceWeb/modules/citizenToolKit/models/Document.php(451): MongoCollection->aggregate(Array)
#1 /home/codev/dev/workspaceWeb/modules/citizenToolKit/models/Document.php(472): Document::storageSpaceByIdAndType('55e042ffe41d754...', 'citoyens', 'image')
#2 /home/codev/dev/workspaceWeb/modules/citizenToolKit/controllers/news/IndexAction.php(429): Document::authorizedToStock('55e042ffe41d754...', 'citoyens', 'image')
#3 [internal function]: IndexAction->run('citoyens', '55e042ffe41d754...', '0', 'true', 'news', NULL)
#4 /home/codev/dev/workspaceWeb/pixelhumain/ph/vendor/yiisoft/yii/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs(Object(IndexAction), Array)
#5 /home/codev/dev/workspaceWeb/pixelhumain/ph/vendor/yiisoft/yii/framework/web/actions/CAction.php(74): CAction->runWithParamsInternal(Object(IndexAction), Object(ReflectionMethod), Array)
#6 /home/codev/dev/workspaceWeb/pixelhumain/ph/vendor/yiisoft/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#7 /home/codev/dev/workspaceWeb/pixelhumain/ph/vendor/yiisoft/yii/framework/web/CController.php(286): CController->runAction(Object(IndexAction))
#8 /home/codev/dev/workspaceWeb/pixelhumain/ph/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(IndexAction), Array)
#9 /home/codev/dev/workspaceWeb/pixelhumain/ph/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run('index')
#10 /home/codev/dev/workspaceWeb/pixelhumain/ph/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('co2/news/index/...')
#11 /home/codev/dev/workspaceWeb/pixelhumain/ph/vendor/yiisoft/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#12 /home/codev/dev/workspaceWeb/pixelhumain/ph/index.php(23): CApplication->run()
#13 {main}</pre> ```

**Comment by clement59** [comment]
Ok aggregate not available with 3.6 version de mongoDB sorry boys. Until Summer 2018 !
https://github.com/nosqlclient/nosqlclient/issues/419
Et le dév est parti au garde à vous ;)
https://medium.com/mongoclient/were-having-a-break-for-a-short-time-a845ac70ebd6
